import EmotionCacheProvider from '@/providers/EmotionCacheProvider'
import ThemeMuiProvider from '@/providers/ThemeMuiProvider'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Roboto } from 'next/font/google'
import { auth } from './api/auth/[...nextauth]/route'
import './globals.css'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // You can pick any weights you use
  variable: '--font-roboto',
  style: ['normal', 'italic'], // Optional
  display: 'swap', // Recommended to avoid FOIT
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <html lang="en">
      <body className={roboto.variable}>
        <SessionProvider session={session}>
          <EmotionCacheProvider>
            <InitColorSchemeScript attribute="class" />
            <AppRouterCacheProvider options={{ enableCssLayer: true }}>
              <ThemeMuiProvider>{children}</ThemeMuiProvider>
            </AppRouterCacheProvider>
          </EmotionCacheProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
