import { AppMaxWidthContainer } from '@/components/layout/AppMaxWidthContainer'
import { auth } from '@/lib/auth'
import EmotionCacheProvider from '@/providers/EmotionCacheProvider'
import ThemeMuiProvider from '@/providers/ThemeMuiProvider'
import '@/styles/vaul.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter'
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Roboto } from 'next/font/google'
import { Toaster } from 'sonner'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // You can pick any weights you use
  variable: '--font-roboto',
  style: ['normal', 'italic'], // Optional
  display: 'swap', // Recommended to avoid FOIT
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.variable}>
        <SessionProvider session={session}>
          <EmotionCacheProvider>
            <InitColorSchemeScript attribute="class" />
            <AppRouterCacheProvider options={{ enableCssLayer: true, key: 'mui' }}>
              <ThemeMuiProvider>
                <AppMaxWidthContainer maxWidth="md">{children}</AppMaxWidthContainer>
                <Toaster position="bottom-center" richColors closeButton />
              </ThemeMuiProvider>
            </AppRouterCacheProvider>
          </EmotionCacheProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
